name: mdsvex

on:
  push:
    paths-ignore:
      - 'site/**'
  pull_request:
    paths-ignore:
      - 'site/**'

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm i -g pnpm@8
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'pnpm'
          cache-dependency-path: '**/pnpm-lock.yaml'
      - run: pnpm i --frozen-lockfile
      - run: pnpm format
        # type-check here as well when it is working
        env:
          CI: true
          name: mdsvex

  build-test:
    name: test-build - node ${{ matrix.node-version }} (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [16, 18]
        os: [ubuntu-latest, macOS-latest, windows-latest]
    steps:
      - uses: actions/checkout@v3
      - run: npm i -g pnpm@8
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
          cache-dependency-path: '**/pnpm-lock.yaml'
      - run: pnpm i --frozen-lockfile
      - run: pnpm test
      - run: pnpm -r build
        env:
          CI: true
          name: mdsvex
